name: B.2 Deploy with Terraform (EC2)

on:
    workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Configure Terraform Cloud token
        env:
          TERRAFORM_CLOUD_TOKEN: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}
        run: |
          echo "credentials \"app.terraform.io\" {
            token = \"$TERRAFORM_CLOUD_TOKEN\"
          }" > ~/.terraformrc
          echo "Terraform Cloud token configured."

      - name: Terraform Init
        run: terraform -chdir=infrastructure_ec2 init

      - name: Terraform Plan
        run: terraform -chdir=infrastructure_ec2 plan

      - name: Terraform Apply
        run: terraform -chdir=infrastructure_ec2 apply -auto-approve

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Install Ansible Docker Dependencies
        run: |
          ansible-galaxy collection install community.docker
          pip install docker

      - name: Configure SSH Access
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $(terraform output ec2_public_ip) >> ~/.ssh/known_hosts

      - name: Create Inventory
        run: |
          echo "[react_server]" > inventory.ini
          echo "$(terraform output ec2_public_ip) ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/nginx_c.pem" >> inventory.ini

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i "$EC2_IP," -u ubuntu --private-key ~/.ssh/id_rsa infrastructure_ec2/ansible_install_docker.yml