name: Docker image pull

on: [push]

jobs:
    test:
        name: Install and test
        runs-on: ubuntu-latest
        steps:
            - name: Pull docker image
              run: docker pull jpg344/react-app-autobuild:latest

            - name: Docker image inspect
              run: docker image inspect jpg344/react-app-test